/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed34ad42-b766-4e15-a85b-72cd805e9d97",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1jjDu1eOQ",
    "aws_user_pools_web_client_id": "3tm6p6sho6espss0h4r44vu9ap",
    "oauth": {}
};


export default awsmobile;
